"""
Dofus Touch connection manager.

Orchestrates the full login flow:
  1. Connect to login server (Primus WebSocket)
  2. Authenticate with game token
  3. Select server
  4. Connect to game server (Primus WebSocket)
  5. Select character
  6. Emit game-ready event → HDV collection can start

Disconnect handling (see DisconnectReason):
  CLIENT_CLOSE  → intentional, no reconnect
  SERVER_CLOSE  → kicked/maintenance/session expired, no reconnect (error set)
  PING_TIMEOUT  → network glitch
  TCP_DROP      → ambiguous network drop

Default (auto_reconnect=False, for short collection runs): any unexpected
mid-session drop ABORTS the run cleanly (a dropped game socket can't resume an
open HDV dialog) and the scheduler re-runs the whole pipeline. With
auto_reconnect=True (long-lived sessions): a full RE-LOGIN is performed (the
game ticket from SelectedServerDataMessage is single-use, so the game socket
cannot simply be reopened), guarded by a circuit breaker (3 drops / 5 min).

Maintenance & game updates:
  - Server not joinable (ServersListMessage.status != 3 / isSelectable false)
    → treated as maintenance, abort with a retry-later error.
  - ProtocolRequired.requiredVersion != PROTOCOL_VERSION, or
    IdentificationFailedForBadVersionMessage → game updated, abort with a
    stop-and-alert error (APP/BUILD versions and protocol must be re-captured).
  classify_error() maps every error to retry-later vs stop-human for schedulers.

Architecture confirmed from live captures:
  Login server:  dt-proxy-production-login.ankama-games.com
  Game server:   host from SelectedServerDataMessage._access (region-dependent)
  Protocol:      Primus WebSocket, JSON messages, version 1595
"""
import logging
import random
import string
import threading
import time
from typing import Optional

from curl_cffi import requests

from .primus_client import PrimusClient, DisconnectReason
from .timing import backoff_delay

log = logging.getLogger(__name__)


def _random_client_key() -> str:
    """
    ClientKeyMessage carries a 21-char alphanumeric key generated by the real
    client (live samples: 'PDuuqm1KTSNERoaRQVEp2', '2w8S8tox7sPIHcJ9fqoH6').
    A fresh value is generated per game connection.
    """
    alphabet = string.ascii_letters + string.digits
    return "".join(random.choices(alphabet, k=21))


# Default login server (from script.js: window.appInfo.server fallback)
LOGIN_SERVER = "https://dt-proxy-production-login.ankama-games.com"

# Primus endpoint path — ✅ confirmed live (session 4 HAR): /primus
PRIMUS_PATH = "/primus"

# Client identity sent in the "connecting" call — confirmed live
APP_VERSION = "3.11.0"
BUILD_VERSION = "1.72.11"
CLIENT = "android"

# Wire protocol version advertised by the server (ProtocolRequired.requiredVersion).
# Confirmed 1595 on 3 captures (login + game). If the server ever requires a
# DIFFERENT version, the game has been updated: message formats may have changed
# and APP_VERSION/BUILD_VERSION above are likely stale → re-capture before trusting.
PROTOCOL_VERSION = 1595

# GameServerInformations.status — 3 = ONLINE/joinable (confirmed live).
# Anything else (offline/starting/saving) means the server is not joinable,
# which during the weekly window means maintenance.
SERVER_STATUS_ONLINE = 3


# Error categories — lets a scheduler decide retry-later vs stop-and-alert.
RETRY_LATER = "retry_later"   # transient: maintenance, network, queue
STOP_HUMAN = "stop_human"     # needs intervention: ban, outdated client
UNKNOWN = "unknown"


def classify_error(error: Optional[str]) -> str:
    """
    Map a session error string to an action category.

    RETRY_LATER → maintenance / network blip / server unavailable: the scheduler
                  should simply try again at the next slot.
    STOP_HUMAN  → account banned or client outdated (game updated): stop the bot,
                  a human must intervene (new account / re-capture protocol).
    """
    if not error:
        return UNKNOWN
    e = error.lower()
    # Needs a human: ban, outdated client (game updated), or a config problem
    # that retrying can't fix (no character on the configured server).
    if "banned" in e or "outdated" in e or "bad_version" in e or "no_characters" in e:
        return STOP_HUMAN
    # Transient: maintenance, network blips, expired ticket (fresh token next run).
    if ("server_unavailable" in e or "server_close" in e or "server_not_found" in e
            or "ping_timeout" in e or "tcp_drop" in e or "circuit_breaker" in e
            or "auth_phase_disconnect" in e or "no_game_server_access" in e
            or "ticket_refused" in e or "game_dropped" in e):
        return RETRY_LATER
    return UNKNOWN


def _primus_query() -> str:
    """
    Primus appends a sticky-session id (STICKER) and a callback id (_primuscb)
    to the WS URL. Confirmed live but origin is client-side. We generate
    plausible values; if the server rejects them, try connecting without.
    """
    import random
    import string
    sticker = "".join(random.choices(string.ascii_letters + string.digits, k=15))
    cb = "".join(random.choices(string.ascii_letters + string.digits, k=7))
    return f"?STICKER={sticker}&_primuscb={cb}"


def _get_config(server_url: str, lang: str = "fr") -> dict:
    """
    Fetch game config from the login server.
    Returns URLs for game servers, assets CDN, etc.
    Called before auth — no credentials needed.
    """
    url = f"{server_url}/config.json"
    resp = requests.get(url, params={"lang": lang}, impersonate="chrome_android", timeout=15)
    resp.raise_for_status()
    return resp.json()


class _CircuitBreaker:
    """
    Opens after max_failures unexpected disconnects within window_s seconds.
    Prevents infinite reconnect loops when the account/IP is being blocked.
    """

    def __init__(self, max_failures: int = 3, window_s: float = 300.0):
        self._timestamps: list[float] = []
        self._max = max_failures
        self._window = window_s

    def record(self):
        now = time.time()
        self._timestamps.append(now)
        # Prune events outside the window
        self._timestamps = [t for t in self._timestamps if now - t <= self._window]

    def is_open(self) -> bool:
        now = time.time()
        recent = [t for t in self._timestamps if now - t <= self._window]
        return len(recent) >= self._max

    def failure_count(self) -> int:
        now = time.time()
        return len([t for t in self._timestamps if now - t <= self._window])


class DofusTouchSession:
    """
    Manages a full Dofus Touch session from auth to in-game.

    Detects maintenance (server not joinable) and game updates (protocol/version
    mismatch), and surfaces a categorisable error (see classify_error). By default
    a mid-session drop aborts cleanly; pass auto_reconnect=True for full-re-login
    resilience on long-lived sessions.

    Usage:
        account_id, token = authenticate("mail@gmail.com", "pw")
        session = DofusTouchSession(game_token=token, server_id=533, account_id=account_id)
        session.connect()
        if session.wait_for_game(timeout=60):
            ...  # in game, session.send_message(...)
        else:
            print(classify_error(session.error))  # retry_later / stop_human
        session.disconnect()
    """

    def __init__(
        self,
        game_token: str,
        server_id: int,
        account_id: str,                     # = HAAPI account_id, sent as login "username"
        character_id: Optional[int] = None,  # None = pick first character
        lang: str = "fr",
        login_server: str = LOGIN_SERVER,
        auto_reconnect: bool = False,
    ):
        self.game_token = game_token
        self.server_id = server_id
        self.account_id = account_id
        self.character_id = character_id
        self.lang = lang
        self.login_server = login_server
        # For a short collection run, a mid-session drop can't cleanly resume the
        # HDV dialog, so the default is to abort and let the scheduler re-run the
        # whole pipeline. Set True only for long-lived/persistent sessions, where
        # reconnect does a FULL re-login (the game ticket is single-use).
        self.auto_reconnect = auto_reconnect

        self._login_client: Optional[PrimusClient] = None
        self._game_client: Optional[PrimusClient] = None
        self._game_ready = threading.Event()
        self._error: Optional[str] = None
        self._message_handlers: dict = {}

        # State built up during the login flow
        self._servers: list = []
        self._characters: list = []
        self._game_server_url: Optional[str] = None
        self._game_server_info: dict = {}   # {address, port, id} for the game "connecting" call
        self._ticket: Optional[str] = None  # game-server ticket from SelectedServerDataMessage

        # Updated when CurrentMapMessage is received; used for NpcGenericActionRequestMessage
        self.map_id: int = -1

        # Anti-cheat sequence counter. The server sends SequenceNumberRequestMessage
        # and we must reply with an incrementing number (1, 2, 3…). Resets to 0 on
        # each new game connection (the count is per-connection, confirmed live).
        self._sequence_number = 0

        # Set True if ProtocolRequired advertises a version != PROTOCOL_VERSION
        # (game updated). Surfaced so the operator knows to re-capture.
        self._protocol_outdated = False

        # Reconnection state
        self._active = False               # False → disconnect() was called, abort reconnects
        self._circuit_breaker = _CircuitBreaker(max_failures=3, window_s=300.0)
        self._reconnect_attempt = 0        # reset to 0 on each successful GameContextCreate

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def on(self, message_type: str):
        """Decorator to register a handler for in-game messages."""
        def decorator(fn):
            self._message_handlers.setdefault(message_type, []).append(fn)
            if self._game_client:
                self._game_client.on(message_type)(fn)
            return fn
        return decorator

    def send_message(self, msg_type: str, data: dict = None):
        """Send a game message (must be called after wait_for_game)."""
        if not self._game_client:
            raise RuntimeError("Not connected to game server yet")
        self._game_client.send_message(msg_type, data)

    def connect(self):
        """Start the login flow (non-blocking, runs in background threads)."""
        self._active = True
        config = _get_config(self.login_server, self.lang)
        log.info("Config loaded. dataUrl=%s", config.get("dataUrl"))

        login_ws_url = self.login_server.replace("https://", "wss://").replace("http://", "ws://")
        login_ws_url += PRIMUS_PATH + _primus_query()

        log.info("Connecting to login server: %s", login_ws_url)
        self._login_client = PrimusClient(login_ws_url)
        self._setup_login_handlers()
        self._login_client.connect(wait=True, timeout=15)

    @property
    def error(self) -> Optional[str]:
        """The reason the session failed, or None. See classify_error()."""
        return self._error

    def wait_for_game(self, timeout: float = 90.0) -> bool:
        """
        Block until the game is fully loaded and character is in-game.
        Returns True if ready within timeout, False otherwise.
        Raises RuntimeError immediately if authentication was refused.
        """
        ready = self._game_ready.wait(timeout)
        # _game_ready is set on BOTH success and failure (failures set it to
        # unblock this wait immediately). So the event being set does NOT mean
        # success — we must check _error independently of `ready`.
        if self._error:
            raise RuntimeError(f"Connection failed: {self._error}")
        return ready

    def disconnect(self):
        """Close all connections and stop any pending reconnect."""
        self._active = False
        if self._game_client:
            self._game_client.disconnect()
        if self._login_client:
            self._login_client.disconnect()

    # ------------------------------------------------------------------ #
    # Shared handlers (login + game)                                      #
    # ------------------------------------------------------------------ #

    def _on_protocol_required(self, msg):
        """
        ProtocolRequired arrives on both servers right after 'connecting'.
        If the required version differs from what we built against, the game
        has been updated: message formats may have changed and our hardcoded
        APP_VERSION/BUILD_VERSION are likely stale. Surface it loudly — the
        login will probably be rejected (IdentificationFailedForBadVersion)
        but this is the earliest, clearest signal that a re-capture is needed.
        """
        required = msg.get("requiredVersion")
        current = msg.get("currentVersion")
        if required is not None and required != PROTOCOL_VERSION:
            log.error("⚠️ PROTOCOL VERSION CHANGED: server requires %s, code built for %s "
                      "(current=%s). Game likely updated — re-capture protocol & bump "
                      "APP_VERSION/BUILD_VERSION before trusting any data.",
                      required, PROTOCOL_VERSION, current)
            self._protocol_outdated = True

    def _on_queue_status(self, msg):
        """
        QueueStatusMessage: a login/connection queue (common right after the
        weekly maintenance when everyone reconnects). position 0/total 0 = no
        queue. We just wait it out (the server advances us); log when queued.
        """
        position = msg.get("position", 0)
        total = msg.get("total", 0)
        if position or total:
            log.info("In login queue: position %s / %s — waiting", position, total)

    # ------------------------------------------------------------------ #
    # Login server handlers                                               #
    # ------------------------------------------------------------------ #

    def _setup_login_handlers(self):
        c = self._login_client

        @c.on("__open__")
        def on_open(msg):
            # "connecting" call on socket open — confirmed live: NO token here,
            # just client identity. The token is sent later in the "login" call.
            log.info("Login socket open → sending 'connecting'")
            c.send_call("connecting", {
                "language": self.lang,
                "server": "login",
                "client": CLIENT,
                "appVersion": APP_VERSION,
                "buildVersion": BUILD_VERSION,
            })

        c.on("ProtocolRequired")(self._on_protocol_required)
        c.on("QueueStatusMessage")(self._on_queue_status)

        @c.on("HelloConnectMessage")
        def on_hello(msg):
            # Server sends salt + key; the login call echoes them back, plus
            # username (= account_id) and the game token. Confirmed live.
            log.info("HelloConnectMessage received → sending 'login'")
            c.send_call("login", {
                "username": self.account_id,
                "token": self.game_token,
                "salt": msg.get("salt", ""),
                "key": msg.get("key", []),
            })

        @c.on("CredentialsAcknowledgementMessage")
        def on_creds_ack(msg):
            log.debug("Credentials acknowledged")

        @c.on("IdentificationSuccessMessage")
        @c.on("IdentificationSuccessWithLoginTokenMessage")
        def on_ident_success(msg):
            log.info("Identification success. nick=%s accountId=%s",
                     msg.get("nickname"), msg.get("accountId"))

        @c.on("ServersListMessage")
        def on_servers(msg):
            self._servers = msg.get("servers", [])
            log.info("Servers list received (%d servers)", len(self._servers))

            target = next((s for s in self._servers if s.get("id") == self.server_id), None)
            if target is None:
                log.error("Target server %d not in the list — wrong DTV_SERVER_ID?", self.server_id)
                self._error = "server_not_found"
                self._game_ready.set()
                return

            status = target.get("status")
            selectable = target.get("isSelectable", False)
            if status != SERVER_STATUS_ONLINE or not selectable:
                # status != 3 / not selectable during the weekly window = maintenance.
                # Abort cleanly: the scheduler should simply retry the next slot.
                log.warning("Server %d (%s) not joinable: status=%s isSelectable=%s "
                            "— likely maintenance, aborting (retry later)",
                            self.server_id, target.get("_name"), status, selectable)
                self._error = f"server_unavailable:status={status}"
                self._game_ready.set()
                return

            log.info("Selecting server id=%d (%s)", self.server_id, target.get("_name"))
            c.send_message("ServerSelectionMessage", {"serverId": self.server_id})

        @c.on("SelectedServerDataMessage")
        def on_server_selected(msg):
            # Confirmed live: the game server HOST is in "_access" (a https:// URL).
            # "address" is an internal AWS IP (172.x) that is NOT routable for us.
            log.info("Server selected: serverId=%s _access=%s address=%s:%s",
                     msg.get("serverId"), msg.get("_access"),
                     msg.get("address"), msg.get("port"))

            self._ticket = msg.get("ticket")
            # The game "connecting" call needs the internal address/port/id verbatim
            self._game_server_info = {
                "address": msg.get("address"),
                "port": msg.get("port"),
                "id": msg.get("serverId"),
            }

            access = msg.get("_access")  # e.g. https://dt-proxy-production-canada.ankama-games.com
            if access:
                host = access.replace("https://", "").replace("http://", "").rstrip("/")
                self._game_server_url = f"wss://{host}{PRIMUS_PATH}{_primus_query()}"
            else:
                log.error("No _access in SelectedServerDataMessage — cannot locate game server")
                self._error = "no_game_server_access"
                self._game_ready.set()
                return

            log.info("Connecting to game server: %s", self._game_server_url)
            self._login_client.send_call("disconnecting", "SWITCHING_TO_GAME")
            self._login_client.disconnect()
            self._connect_to_game_server()

        @c.on("IdentificationFailedForBadVersionMessage")
        def on_bad_version(msg):
            # Definitive "your client is outdated" signal — the game was updated.
            # Don't reconnect; the operator must bump APP/BUILD version + re-capture.
            required = msg.get("requiredVersion") or msg.get("version")
            log.error("⚠️ CLIENT OUTDATED (IdentificationFailedForBadVersion): "
                      "server wants version %s, we send app=%s build=%s. "
                      "Game updated — STOP and re-capture the protocol.",
                      required, APP_VERSION, BUILD_VERSION)
            self._error = "outdated_client_needs_update"
            self._active = False
            self._game_ready.set()

        @c.on("IdentificationFailedBannedMessage")
        def on_banned(msg):
            # Account banned — never reconnect, raise loudly.
            log.error("⛔ ACCOUNT BANNED (IdentificationFailedBannedMessage): %s", msg)
            self._error = "account_banned"
            self._active = False
            self._game_ready.set()

        @c.on("IdentificationFailedMessage")
        def on_ident_failed(msg):
            reason = msg.get("reason") or msg.get("_messageType", "unknown")
            log.error("Identification failed: %s", reason)
            self._error = reason
            self._game_ready.set()  # unblock wait_for_game() immediately

    # ------------------------------------------------------------------ #
    # Game server handlers                                                #
    # ------------------------------------------------------------------ #

    def _connect_to_game_server(self):
        self._sequence_number = 0  # per-connection counter, reset on (re)connect
        self._game_client = PrimusClient(self._game_server_url)
        self._setup_game_handlers()

        # Register any user-provided handlers (e.g. from HdvCollector)
        for msg_type, handlers in self._message_handlers.items():
            for handler in handlers:
                self._game_client.on(msg_type)(handler)

        self._game_client.connect(wait=True, timeout=15)

    def _setup_game_handlers(self):
        c = self._game_client
        ticket = self._ticket or self.game_token

        c.on("ProtocolRequired")(self._on_protocol_required)
        c.on("QueueStatusMessage")(self._on_queue_status)

        @c.on("__open__")
        def on_game_open(msg):
            # Game "connecting" call carries the server's internal address/port/id
            # (from SelectedServerDataMessage). Confirmed live.
            log.info("Game socket open → sending 'connecting'")
            c.send_call("connecting", {
                "language": self.lang,
                "server": self._game_server_info,
                "client": CLIENT,
                "appVersion": APP_VERSION,
                "buildVersion": BUILD_VERSION,
            })

        @c.on("HelloGameMessage")
        def on_hello_game(msg):
            log.info("HelloGameMessage → sending AuthenticationTicketMessage")
            c.send_message("AuthenticationTicketMessage", {
                "ticket": ticket,
                "lang": self.lang,
            })

        @c.on("AuthenticationTicketAcceptedMessage")
        def on_ticket_accepted(msg):
            log.info("Auth ticket accepted → requesting character list")
            # Real client sends a 'pingSession' call here (a session nonce) before
            # the character list. Replicated for client-parity / anti-fingerprinting.
            c.send_call("pingSession", random.randint(100_000_000, 999_999_999))
            c.send_message("CharactersListRequestMessage", {})

        @c.on("SequenceNumberRequestMessage")
        def on_sequence_request(msg):
            # Anti-cheat: the server periodically asks for a sequence number; the
            # client replies with a per-connection incrementing counter. Missing
            # this makes the session look abnormal and may gate game actions.
            self._sequence_number += 1
            c.send_message("SequenceNumberMessage", {"number": self._sequence_number})
            log.debug("SequenceNumberRequest → replied number=%d", self._sequence_number)

        @c.on("AuthenticationTicketRefusedMessage")
        def on_ticket_refused(msg):
            log.error("Auth ticket refused — token expired or invalid")
            self._error = "ticket_refused"
            self._active = False
            self._game_ready.set()

        @c.on("CharactersListMessage")
        def on_char_list(msg):
            chars = msg.get("characters", [])
            log.info("Character list: %d characters", len(chars))
            self._characters = chars

            if not chars:
                log.error("No characters on this server")
                self._error = "no_characters"
                self._game_ready.set()
                return

            if self.character_id:
                selected = next((ch for ch in chars if ch.get("id") == self.character_id), None)
                if not selected:
                    log.warning("Character id=%d not found, using first", self.character_id)
                    selected = chars[0]
            else:
                selected = chars[0]

            log.info("Selecting character: %s (id=%s)", selected.get("name"), selected.get("id"))
            c.send_message("CharacterSelectionMessage", {"id": selected["id"]})

        @c.on("CharacterSelectedSuccessMessage")
        def on_char_selected(msg):
            log.info("Character selected → sending context ready")
            # Real client sends ClientKeyMessage just before creating the game
            # context. Replicated for client-parity / anti-fingerprinting.
            c.send_message("ClientKeyMessage", {"key": _random_client_key()})
            c.send_message("GameContextCreateRequestMessage", {})

        @c.on("GameContextCreateMessage")
        def on_context_created(msg):
            log.info("Game context created — session is ready!")
            self._reconnect_attempt = 0  # reset backoff counter on successful connect
            self._game_ready.set()

        @c.on("CurrentMapMessage")
        def on_current_map(msg):
            self.map_id = msg.get("mapId", -1)
            log.debug("Map updated: mapId=%d", self.map_id)

        @c.on("ConnectionFailedMessage")
        def on_conn_failed(msg):
            log.error("Connection failed: %s", msg)

        @c.on("__close__")
        def on_game_close(msg):
            reason = msg.get("disconnect_reason")
            self._handle_game_disconnect(reason)

    # ------------------------------------------------------------------ #
    # Reconnection logic                                                  #
    # ------------------------------------------------------------------ #

    def _handle_game_disconnect(self, reason: Optional[DisconnectReason]):
        """
        Decide what to do when the game WebSocket closes.
        Called from the PrimusClient receive thread — must not block.
        """
        if reason == DisconnectReason.CLIENT_CLOSE:
            log.info("Game connection closed by client — no reconnect")
            return

        if reason == DisconnectReason.SERVER_CLOSE:
            log.warning("Server closed the connection (kick / maintenance / session expired)")
            self._error = "server_close"
            self._game_ready.set()
            return

        # PING_TIMEOUT or TCP_DROP beyond this point
        if not self._active:
            log.info("Session is shutting down — ignoring disconnect [%s]",
                     reason.value if reason else "unknown")
            return

        # Disconnect during auth phase (before GameContextCreateMessage) →
        # likely a bad token; re-auth is the caller's responsibility
        if not self._game_ready.is_set():
            log.error("Disconnected during auth phase [%s] — token may be invalid",
                      reason.value if reason else "unknown")
            self._error = f"auth_phase_disconnect:{reason.value if reason else 'unknown'}"
            self._game_ready.set()
            return

        # Mid-session drop after we were in-game. For a collection run we don't
        # try to resume (the HDV dialog state is gone) — abort cleanly and let the
        # scheduler re-run. Only attempt reconnect if explicitly enabled.
        if not self.auto_reconnect:
            log.warning("Game dropped [%s] — aborting run (auto_reconnect off); "
                        "scheduler should retry.", reason.value if reason else "unknown")
            self._error = f"game_dropped:{reason.value if reason else 'unknown'}"
            self._game_ready.set()
            return

        self._circuit_breaker.record()
        if self._circuit_breaker.is_open():
            log.error(
                "Circuit breaker open (%d disconnects in %.0fs) — stopping reconnect attempts",
                self._circuit_breaker.failure_count(),
                self._circuit_breaker._window,
            )
            self._error = "circuit_breaker_open"
            self._game_ready.set()
            return

        log.info(
            "Game disconnected [%s] — reconnect attempt %d in ~%.0fs",
            reason.value if reason else "unknown",
            self._reconnect_attempt + 1,
            min(2.0 * (2 ** self._reconnect_attempt), 60.0),
        )
        threading.Thread(target=self._reconnect_game, daemon=True).start()

    def _reconnect_game(self):
        """Run in a background thread: wait backoff, then reconnect."""
        if not self._active:
            return

        attempt = self._reconnect_attempt
        self._reconnect_attempt += 1

        backoff_delay(attempt)

        if not self._active:
            return

        log.info("Reconnecting (full re-login, attempt %d)…", attempt + 1)
        self._game_ready.clear()

        try:
            # A game-server ticket is SINGLE-USE; reopening the game socket with the
            # old ticket would be refused. Redo the FULL login flow (login server →
            # fresh ServerSelection → fresh ticket → game), reusing the HAAPI
            # game_token. If that token is itself expired, the login handlers set
            # _error (IdentificationFailed) and we abort cleanly rather than loop.
            self.connect()
        except Exception as e:
            log.error("Reconnect attempt %d failed: %s", attempt + 1, e)
            self._circuit_breaker.record()
            if self._circuit_breaker.is_open():
                log.error("Circuit breaker open after failed reconnect — giving up")
                self._error = "circuit_breaker_open"
                self._game_ready.set()
            elif self._active:
                # connect() raised before any client could fire __close__, so we
                # reschedule manually
                threading.Thread(target=self._reconnect_game, daemon=True).start()
