"""
Dofus Touch connection manager.

Orchestrates the full login flow:
  1. Connect to login server (Primus WebSocket)
  2. Authenticate with game token
  3. Select server
  4. Connect to game server (Primus WebSocket)
  5. Select character
  6. Emit game-ready event → HDV collection can start

Reconnection behaviour (4 distinct disconnect cases):
  CLIENT_CLOSE  → intentional, no reconnect
  SERVER_CLOSE  → kicked/maintenance, no reconnect (raise error)
  PING_TIMEOUT  → network glitch, reconnect with exponential backoff
  TCP_DROP      → ambiguous, reconnect with exponential backoff + caution

Circuit breaker: after 3 unexpected disconnects in 5 minutes, give up.

Architecture confirmed from script.js + PCAPdroid captures:
  Login server:  dt-proxy-production-login.ankama-games.com  (TCP → TLS)
  Game server:   dt-proxy-production-france.ankama-games.com (TCP → TLS)
  Protocol:      Primus WebSocket, JSON messages
"""
import logging
import random
import string
import threading
import time
from typing import Optional

from curl_cffi import requests

from .primus_client import PrimusClient, DisconnectReason
from .timing import backoff_delay

log = logging.getLogger(__name__)


def _random_client_key() -> str:
    """
    ClientKeyMessage carries a 21-char alphanumeric key generated by the real
    client (live samples: 'PDuuqm1KTSNERoaRQVEp2', '2w8S8tox7sPIHcJ9fqoH6').
    A fresh value is generated per game connection.
    """
    alphabet = string.ascii_letters + string.digits
    return "".join(random.choices(alphabet, k=21))


# Default login server (from script.js: window.appInfo.server fallback)
LOGIN_SERVER = "https://dt-proxy-production-login.ankama-games.com"

# Primus endpoint path — ✅ confirmed live (session 4 HAR): /primus
PRIMUS_PATH = "/primus"

# Client identity sent in the "connecting" call — confirmed live
APP_VERSION = "3.11.0"
BUILD_VERSION = "1.72.11"
CLIENT = "android"


def _primus_query() -> str:
    """
    Primus appends a sticky-session id (STICKER) and a callback id (_primuscb)
    to the WS URL. Confirmed live but origin is client-side. We generate
    plausible values; if the server rejects them, try connecting without.
    """
    import random
    import string
    sticker = "".join(random.choices(string.ascii_letters + string.digits, k=15))
    cb = "".join(random.choices(string.ascii_letters + string.digits, k=7))
    return f"?STICKER={sticker}&_primuscb={cb}"


def _get_config(server_url: str, lang: str = "fr") -> dict:
    """
    Fetch game config from the login server.
    Returns URLs for game servers, assets CDN, etc.
    Called before auth — no credentials needed.
    """
    url = f"{server_url}/config.json"
    resp = requests.get(url, params={"lang": lang}, impersonate="chrome_android", timeout=15)
    resp.raise_for_status()
    return resp.json()


class _CircuitBreaker:
    """
    Opens after max_failures unexpected disconnects within window_s seconds.
    Prevents infinite reconnect loops when the account/IP is being blocked.
    """

    def __init__(self, max_failures: int = 3, window_s: float = 300.0):
        self._timestamps: list[float] = []
        self._max = max_failures
        self._window = window_s

    def record(self):
        now = time.time()
        self._timestamps.append(now)
        # Prune events outside the window
        self._timestamps = [t for t in self._timestamps if now - t <= self._window]

    def is_open(self) -> bool:
        now = time.time()
        recent = [t for t in self._timestamps if now - t <= self._window]
        return len(recent) >= self._max

    def failure_count(self) -> int:
        now = time.time()
        return len([t for t in self._timestamps if now - t <= self._window])


class DofusTouchSession:
    """
    Manages a full Dofus Touch session from auth to in-game, with reconnection.

    Usage:
        account_id, token = authenticate("mail@gmail.com", "pw")
        session = DofusTouchSession(game_token=token, server_id=533, account_id=account_id)
        session.connect()
        session.wait_for_game(timeout=60)
        # Now in game, can use session.send_message(...)
        session.disconnect()
    """

    def __init__(
        self,
        game_token: str,
        server_id: int,
        account_id: str,                     # = HAAPI account_id, sent as login "username"
        character_id: Optional[int] = None,  # None = pick first character
        lang: str = "fr",
        login_server: str = LOGIN_SERVER,
    ):
        self.game_token = game_token
        self.server_id = server_id
        self.account_id = account_id
        self.character_id = character_id
        self.lang = lang
        self.login_server = login_server

        self._login_client: Optional[PrimusClient] = None
        self._game_client: Optional[PrimusClient] = None
        self._game_ready = threading.Event()
        self._error: Optional[str] = None
        self._message_handlers: dict = {}

        # State built up during the login flow
        self._servers: list = []
        self._characters: list = []
        self._game_server_url: Optional[str] = None
        self._game_server_info: dict = {}   # {address, port, id} for the game "connecting" call
        self._ticket: Optional[str] = None  # game-server ticket from SelectedServerDataMessage

        # Updated when CurrentMapMessage is received; used for NpcGenericActionRequestMessage
        self.map_id: int = -1

        # Anti-cheat sequence counter. The server sends SequenceNumberRequestMessage
        # and we must reply with an incrementing number (1, 2, 3…). Resets to 0 on
        # each new game connection (the count is per-connection, confirmed live).
        self._sequence_number = 0

        # Reconnection state
        self._active = False               # False → disconnect() was called, abort reconnects
        self._circuit_breaker = _CircuitBreaker(max_failures=3, window_s=300.0)
        self._reconnect_attempt = 0        # reset to 0 on each successful GameContextCreate

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def on(self, message_type: str):
        """Decorator to register a handler for in-game messages."""
        def decorator(fn):
            self._message_handlers.setdefault(message_type, []).append(fn)
            if self._game_client:
                self._game_client.on(message_type)(fn)
            return fn
        return decorator

    def send_message(self, msg_type: str, data: dict = None):
        """Send a game message (must be called after wait_for_game)."""
        if not self._game_client:
            raise RuntimeError("Not connected to game server yet")
        self._game_client.send_message(msg_type, data)

    def connect(self):
        """Start the login flow (non-blocking, runs in background threads)."""
        self._active = True
        config = _get_config(self.login_server, self.lang)
        log.info("Config loaded. dataUrl=%s", config.get("dataUrl"))

        login_ws_url = self.login_server.replace("https://", "wss://").replace("http://", "ws://")
        login_ws_url += PRIMUS_PATH + _primus_query()

        log.info("Connecting to login server: %s", login_ws_url)
        self._login_client = PrimusClient(login_ws_url)
        self._setup_login_handlers()
        self._login_client.connect(wait=True, timeout=15)

    def wait_for_game(self, timeout: float = 90.0) -> bool:
        """
        Block until the game is fully loaded and character is in-game.
        Returns True if ready within timeout, False otherwise.
        Raises RuntimeError immediately if authentication was refused.
        """
        ready = self._game_ready.wait(timeout)
        # _game_ready is set on BOTH success and failure (failures set it to
        # unblock this wait immediately). So the event being set does NOT mean
        # success — we must check _error independently of `ready`.
        if self._error:
            raise RuntimeError(f"Connection failed: {self._error}")
        return ready

    def disconnect(self):
        """Close all connections and stop any pending reconnect."""
        self._active = False
        if self._game_client:
            self._game_client.disconnect()
        if self._login_client:
            self._login_client.disconnect()

    # ------------------------------------------------------------------ #
    # Login server handlers                                               #
    # ------------------------------------------------------------------ #

    def _setup_login_handlers(self):
        c = self._login_client

        @c.on("__open__")
        def on_open(msg):
            # "connecting" call on socket open — confirmed live: NO token here,
            # just client identity. The token is sent later in the "login" call.
            log.info("Login socket open → sending 'connecting'")
            c.send_call("connecting", {
                "language": self.lang,
                "server": "login",
                "client": CLIENT,
                "appVersion": APP_VERSION,
                "buildVersion": BUILD_VERSION,
            })

        @c.on("HelloConnectMessage")
        def on_hello(msg):
            # Server sends salt + key; the login call echoes them back, plus
            # username (= account_id) and the game token. Confirmed live.
            log.info("HelloConnectMessage received → sending 'login'")
            c.send_call("login", {
                "username": self.account_id,
                "token": self.game_token,
                "salt": msg.get("salt", ""),
                "key": msg.get("key", []),
            })

        @c.on("CredentialsAcknowledgementMessage")
        def on_creds_ack(msg):
            log.debug("Credentials acknowledged")

        @c.on("IdentificationSuccessMessage")
        @c.on("IdentificationSuccessWithLoginTokenMessage")
        def on_ident_success(msg):
            log.info("Identification success. nick=%s accountId=%s",
                     msg.get("nickname"), msg.get("accountId"))

        @c.on("ServersListMessage")
        def on_servers(msg):
            self._servers = msg.get("servers", [])
            log.info("Servers list received (%d servers)", len(self._servers))
            log.info("Selecting server id=%d", self.server_id)
            c.send_message("ServerSelectionMessage", {"serverId": self.server_id})

        @c.on("SelectedServerDataMessage")
        def on_server_selected(msg):
            # Confirmed live: the game server HOST is in "_access" (a https:// URL).
            # "address" is an internal AWS IP (172.x) that is NOT routable for us.
            log.info("Server selected: serverId=%s _access=%s address=%s:%s",
                     msg.get("serverId"), msg.get("_access"),
                     msg.get("address"), msg.get("port"))

            self._ticket = msg.get("ticket")
            # The game "connecting" call needs the internal address/port/id verbatim
            self._game_server_info = {
                "address": msg.get("address"),
                "port": msg.get("port"),
                "id": msg.get("serverId"),
            }

            access = msg.get("_access")  # e.g. https://dt-proxy-production-canada.ankama-games.com
            if access:
                host = access.replace("https://", "").replace("http://", "").rstrip("/")
                self._game_server_url = f"wss://{host}{PRIMUS_PATH}{_primus_query()}"
            else:
                log.error("No _access in SelectedServerDataMessage — cannot locate game server")
                self._error = "no_game_server_access"
                self._game_ready.set()
                return

            log.info("Connecting to game server: %s", self._game_server_url)
            self._login_client.send_call("disconnecting", "SWITCHING_TO_GAME")
            self._login_client.disconnect()
            self._connect_to_game_server()

        @c.on("IdentificationFailedMessage")
        @c.on("IdentificationFailedBannedMessage")
        @c.on("IdentificationFailedForBadVersionMessage")
        def on_ident_failed(msg):
            reason = msg.get("reason") or msg.get("_messageType", "unknown")
            log.error("Identification failed: %s", reason)
            self._error = reason
            self._game_ready.set()  # unblock wait_for_game() immediately

    # ------------------------------------------------------------------ #
    # Game server handlers                                                #
    # ------------------------------------------------------------------ #

    def _connect_to_game_server(self):
        self._sequence_number = 0  # per-connection counter, reset on (re)connect
        self._game_client = PrimusClient(self._game_server_url)
        self._setup_game_handlers()

        # Register any user-provided handlers (e.g. from HdvCollector)
        for msg_type, handlers in self._message_handlers.items():
            for handler in handlers:
                self._game_client.on(msg_type)(handler)

        self._game_client.connect(wait=True, timeout=15)

    def _setup_game_handlers(self):
        c = self._game_client
        ticket = self._ticket or self.game_token

        @c.on("__open__")
        def on_game_open(msg):
            # Game "connecting" call carries the server's internal address/port/id
            # (from SelectedServerDataMessage). Confirmed live.
            log.info("Game socket open → sending 'connecting'")
            c.send_call("connecting", {
                "language": self.lang,
                "server": self._game_server_info,
                "client": CLIENT,
                "appVersion": APP_VERSION,
                "buildVersion": BUILD_VERSION,
            })

        @c.on("HelloGameMessage")
        def on_hello_game(msg):
            log.info("HelloGameMessage → sending AuthenticationTicketMessage")
            c.send_message("AuthenticationTicketMessage", {
                "ticket": ticket,
                "lang": self.lang,
            })

        @c.on("AuthenticationTicketAcceptedMessage")
        def on_ticket_accepted(msg):
            log.info("Auth ticket accepted → requesting character list")
            # Real client sends a 'pingSession' call here (a session nonce) before
            # the character list. Replicated for client-parity / anti-fingerprinting.
            c.send_call("pingSession", random.randint(100_000_000, 999_999_999))
            c.send_message("CharactersListRequestMessage", {})

        @c.on("SequenceNumberRequestMessage")
        def on_sequence_request(msg):
            # Anti-cheat: the server periodically asks for a sequence number; the
            # client replies with a per-connection incrementing counter. Missing
            # this makes the session look abnormal and may gate game actions.
            self._sequence_number += 1
            c.send_message("SequenceNumberMessage", {"number": self._sequence_number})
            log.debug("SequenceNumberRequest → replied number=%d", self._sequence_number)

        @c.on("AuthenticationTicketRefusedMessage")
        def on_ticket_refused(msg):
            log.error("Auth ticket refused — token expired or invalid")
            self._error = "ticket_refused"
            self._active = False
            self._game_ready.set()

        @c.on("CharactersListMessage")
        def on_char_list(msg):
            chars = msg.get("characters", [])
            log.info("Character list: %d characters", len(chars))
            self._characters = chars

            if not chars:
                log.error("No characters on this server")
                self._error = "no_characters"
                self._game_ready.set()
                return

            if self.character_id:
                selected = next((ch for ch in chars if ch.get("id") == self.character_id), None)
                if not selected:
                    log.warning("Character id=%d not found, using first", self.character_id)
                    selected = chars[0]
            else:
                selected = chars[0]

            log.info("Selecting character: %s (id=%s)", selected.get("name"), selected.get("id"))
            c.send_message("CharacterSelectionMessage", {"id": selected["id"]})

        @c.on("CharacterSelectedSuccessMessage")
        def on_char_selected(msg):
            log.info("Character selected → sending context ready")
            # Real client sends ClientKeyMessage just before creating the game
            # context. Replicated for client-parity / anti-fingerprinting.
            c.send_message("ClientKeyMessage", {"key": _random_client_key()})
            c.send_message("GameContextCreateRequestMessage", {})

        @c.on("GameContextCreateMessage")
        def on_context_created(msg):
            log.info("Game context created — session is ready!")
            self._reconnect_attempt = 0  # reset backoff counter on successful connect
            self._game_ready.set()

        @c.on("CurrentMapMessage")
        def on_current_map(msg):
            self.map_id = msg.get("mapId", -1)
            log.debug("Map updated: mapId=%d", self.map_id)

        @c.on("ConnectionFailedMessage")
        def on_conn_failed(msg):
            log.error("Connection failed: %s", msg)

        @c.on("__close__")
        def on_game_close(msg):
            reason = msg.get("disconnect_reason")
            self._handle_game_disconnect(reason)

    # ------------------------------------------------------------------ #
    # Reconnection logic                                                  #
    # ------------------------------------------------------------------ #

    def _handle_game_disconnect(self, reason: Optional[DisconnectReason]):
        """
        Decide what to do when the game WebSocket closes.
        Called from the PrimusClient receive thread — must not block.
        """
        if reason == DisconnectReason.CLIENT_CLOSE:
            log.info("Game connection closed by client — no reconnect")
            return

        if reason == DisconnectReason.SERVER_CLOSE:
            log.warning("Server closed the connection (kick / maintenance / session expired)")
            self._error = "server_close"
            self._game_ready.set()
            return

        # PING_TIMEOUT or TCP_DROP beyond this point
        if not self._active:
            log.info("Session is shutting down — ignoring disconnect [%s]",
                     reason.value if reason else "unknown")
            return

        # Disconnect during auth phase (before GameContextCreateMessage) →
        # likely a bad token; re-auth is the caller's responsibility
        if not self._game_ready.is_set():
            log.error("Disconnected during auth phase [%s] — token may be invalid",
                      reason.value if reason else "unknown")
            self._error = f"auth_phase_disconnect:{reason.value if reason else 'unknown'}"
            self._game_ready.set()
            return

        self._circuit_breaker.record()
        if self._circuit_breaker.is_open():
            log.error(
                "Circuit breaker open (%d disconnects in %.0fs) — stopping reconnect attempts",
                self._circuit_breaker.failure_count(),
                self._circuit_breaker._window,
            )
            self._error = "circuit_breaker_open"
            self._game_ready.set()
            return

        log.info(
            "Game disconnected [%s] — reconnect attempt %d in ~%.0fs",
            reason.value if reason else "unknown",
            self._reconnect_attempt + 1,
            min(2.0 * (2 ** self._reconnect_attempt), 60.0),
        )
        threading.Thread(target=self._reconnect_game, daemon=True).start()

    def _reconnect_game(self):
        """Run in a background thread: wait backoff, then reconnect."""
        if not self._active:
            return

        attempt = self._reconnect_attempt
        self._reconnect_attempt += 1

        backoff_delay(attempt)

        if not self._active:
            return

        log.info("Reconnecting to game server (attempt %d)…", attempt + 1)
        self._game_ready.clear()

        try:
            self._connect_to_game_server()
        except Exception as e:
            log.error("Reconnect attempt %d failed: %s", attempt + 1, e)
            self._circuit_breaker.record()
            if self._circuit_breaker.is_open():
                log.error("Circuit breaker open after failed reconnect — giving up")
                self._error = "circuit_breaker_open"
                self._game_ready.set()
            elif self._active:
                # _connect_to_game_server raised before creating a client that could
                # fire __close__, so we reschedule manually
                threading.Thread(target=self._reconnect_game, daemon=True).start()
